import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <video autoPlay loop muted playsInline className='absolute w-full h-full -z-10 object-cover'>
          <source src="/landing/background/background.webm" type='video/webm' />
        </video>
      <div className='w-screen h-screen flex justify-center items-center p-5'>
        <h1 className='text-white font-bold text-5xl md:text-6xl lg:text-6xl drop-shadow[0_5px_3px_rgba(0.0.0.4)]'>
          Hey <br /> I'm  <a href='#' className='text-purple-200'>Anas Masti</a> <br/> Web developer
        </h1>

      </div>

    </div>
  )
}
